export const VENEZUELA_STATES = [
  "Amazonas",
  "AnzoÃ¡tegui",
  "Apure",
  "Aragua",
  "Barinas",
  "BolÃ­var",
  "Carabobo",
  "Cojedes",
  "Delta Amacuro",
  "Distrito Capital",
  "FalcÃ³n",
  "GuÃ¡rico",
  "Lara",
  "MÃ©rida",
  "Miranda",
  "Monagas",
  "Nueva Esparta",
  "Portuguesa",
  "Sucre",
  "TÃ¡chira",
  "Trujillo",
  "La Guaira",
  "Yaracuy",
  "Zulia",
] as const;

export const VENEZUELA_CITIES_BY_STATE: Record<(typeof VENEZUELA_STATES)[number], string[]> = {
  Amazonas: ["Puerto Ayacucho", "San Fernando de Atabapo", "La Esmeralda", "Maroa", "San Carlos de RÃ­o Negro"],
  "AnzoÃ¡tegui": ["Barcelona", "Puerto La Cruz", "LecherÃ­a", "El Tigre", "Anaco", "Guanta"],
  Apure: ["San Fernando de Apure", "Guasdualito", "Achaguas", "Biruaca"],
  Aragua: ["Maracay", "Turmero", "La Victoria", "Cagua", "El LimÃ³n"],
  Barinas: ["Barinas", "Barinitas", "SocopÃ³", "Santa BÃ¡rbara de Barinas"],
  "BolÃ­var": ["Ciudad Guayana", "Ciudad BolÃ­var", "Upata", "Tumeremo", "El Callao"],
  Carabobo: ["Valencia", "Puerto Cabello", "Naguanagua", "Guacara", "San Diego"],
  Cojedes: ["San Carlos", "Tinaquillo", "Tinaco"],
  "Delta Amacuro": ["Tucupita", "Pedernales"],
  "Distrito Capital": ["Caracas"],
  "FalcÃ³n": ["Coro", "Punto Fijo", "Chichiriviche", "Tucacas"],
  "GuÃ¡rico": ["San Juan de los Morros", "Calabozo", "Valle de la Pascua", "Zaraza"],
  Lara: ["Barquisimeto", "Cabudare", "Carora", "El Tocuyo", "QuÃ­bor"],
  "MÃ©rida": ["MÃ©rida", "Ejido", "El VigÃ­a", "Tovar", "Lagunillas"],
  Miranda: ["Los Teques", "Guarenas", "Guatire", "Ocumare del Tuy", "Charallave", "Higuerote"],
  Monagas: ["MaturÃ­n", "Punta de Mata", "Caripito", "Caripe"],
  "Nueva Esparta": ["La AsunciÃ³n", "Porlamar", "Pampatar", "Juan Griego"],
  Portuguesa: ["Guanare", "Acarigua", "Araure", "TurÃ©n"],
  Sucre: ["CumanÃ¡", "CarÃºpano", "GÃ¼iria", "RÃ­o Caribe"],
  "TÃ¡chira": ["San CristÃ³bal", "TÃ¡riba", "Rubio", "La Grita", "San Antonio del TÃ¡chira"],
  Trujillo: ["Trujillo", "Valera", "BoconÃ³", "MotatÃ¡n"],
  "La Guaira": ["La Guaira", "Catia La Mar", "MaiquetÃ­a", "Carayaca", "NaiguatÃ¡"],
  Yaracuy: ["San Felipe", "Yaritagua", "Chivacoa", "Nirgua"],
  Zulia: ["Maracaibo", "Cabimas", "Ciudad Ojeda", "San Francisco", "Machiques"],
};

