export const VENEZUELA_STATES = [
  "Amazonas",
  "Anzoátegui",
  "Apure",
  "Aragua",
  "Barinas",
  "Bolívar",
  "Carabobo",
  "Cojedes",
  "Delta Amacuro",
  "Distrito Capital",
  "Falcón",
  "Guárico",
  "Lara",
  "Mérida",
  "Miranda",
  "Monagas",
  "Nueva Esparta",
  "Portuguesa",
  "Sucre",
  "Táchira",
  "Trujillo",
  "La Guaira",
  "Yaracuy",
  "Zulia",
] as const;

export const VENEZUELA_CITIES_BY_STATE: Record<(typeof VENEZUELA_STATES)[number], string[]> = {
  Amazonas: ["Puerto Ayacucho", "San Fernando de Atabapo", "La Esmeralda", "Maroa", "San Carlos de Río Negro"],
  "Anzoátegui": ["Barcelona", "Puerto La Cruz", "Lechería", "El Tigre", "Anaco", "Guanta"],
  Apure: ["San Fernando de Apure", "Guasdualito", "Achaguas", "Biruaca"],
  Aragua: ["Maracay", "Turmero", "La Victoria", "Cagua", "El Limón"],
  Barinas: ["Barinas", "Barinitas", "Socopó", "Santa Bárbara de Barinas"],
  "Bolívar": ["Ciudad Guayana", "Ciudad Bolívar", "Upata", "Tumeremo", "El Callao"],
  Carabobo: ["Valencia", "Puerto Cabello", "Naguanagua", "Guacara", "San Diego"],
  Cojedes: ["San Carlos", "Tinaquillo", "Tinaco"],
  "Delta Amacuro": ["Tucupita", "Pedernales"],
  "Distrito Capital": ["Caracas"],
  "Falcón": ["Coro", "Punto Fijo", "Chichiriviche", "Tucacas"],
  "Guárico": ["San Juan de los Morros", "Calabozo", "Valle de la Pascua", "Zaraza"],
  Lara: ["Barquisimeto", "Cabudare", "Carora", "El Tocuyo", "Quíbor"],
  "Mérida": ["Mérida", "Ejido", "El Vigía", "Tovar", "Lagunillas"],
  Miranda: ["Los Teques", "Guarenas", "Guatire", "Ocumare del Tuy", "Charallave", "Higuerote"],
  Monagas: ["Maturín", "Punta de Mata", "Caripito", "Caripe"],
  "Nueva Esparta": ["La Asunción", "Porlamar", "Pampatar", "Juan Griego"],
  Portuguesa: ["Guanare", "Acarigua", "Araure", "Turén"],
  Sucre: ["Cumaná", "Carúpano", "Güiria", "Río Caribe"],
  "Táchira": ["San Cristóbal", "Táriba", "Rubio", "La Grita", "San Antonio del Táchira"],
  Trujillo: ["Trujillo", "Valera", "Boconó", "Motatán"],
  "La Guaira": ["La Guaira", "Catia La Mar", "Maiquetía", "Carayaca", "Naiguatá"],
  Yaracuy: ["San Felipe", "Yaritagua", "Chivacoa", "Nirgua"],
  Zulia: ["Maracaibo", "Cabimas", "Ciudad Ojeda", "San Francisco", "Machiques"],
};

